import uuid
import subprocess
import tempfile
import os
from google.adk.tools import ToolContext
from google.genai import types
from google.adk.tools import FunctionTool
import logging
from typing import Dict, Any, Optional
import re

from src.services.adk.tts.factory import get_tts_provider

logger = logging.getLogger(__name__)

# Compile regex patterns at module level for performance
EMOJI_PATTERN = re.compile(
    '['
    '\U0001f600-\U0001f64f'  # emoticons
    '\U0001f300-\U0001f5ff'  # symbols & pictographs
    '\U0001f680-\U0001f6ff'  # transport & map symbols
    '\U0001f1e0-\U0001f1ff'  # flags (iOS)
    '\U00002702-\U000027b0'
    '\U000024c2-\U0001f251'
    '\u2600-\u26ff'          # misc symbols
    '\u2700-\u27bf'          # dingbats
    '\U0001F900-\U0001F9FF'  # Supplemental Symbols and Pictographs
    '\U0001FA70-\U0001FAFF'  # Symbols and Pictographs Extended-A
    '\u200d'                 # Zero width joiner
    '\ufe0f'                 # Variation selector
    ']+', flags=re.UNICODE)

BRACKET_PATTERN = re.compile(r'\[[^\]]{1,20}\]')
ASTERISK_PATTERN = re.compile(r'\*+')
UNDERSCORE_PATTERN = re.compile(r'_+')
HASH_PATTERN = re.compile(r'#+')
MEDIA_TAG_PATTERN = re.compile(r'\[?(?:VIDEO_LINK|IMAGE_LINK|AUDIO_LINK)[^\]\s]*\s*(?:https?://[^\s\]]+)?\]?', flags=re.IGNORECASE)
URL_PATTERN = re.compile(r'https?://[^\s]+')
SPACE_PATTERN = re.compile(r'\s+')

def _clean_text_for_tts(text: str) -> str:
    """Removes emojis, markdown formatting, and other symbols that TTS might read literally."""
    if not text:
        return text
    
    # Using the emoji package to accurately remove all emojis
    try:
        import emoji
        text = emoji.replace_emoji(text, replace='')
    except ImportError:
        logger.warning("emoji package not installed, using regex fallback for emoji removal")
        
    # Always apply regex to catch any remaining emojis (or if package failed)
    text = EMOJI_PATTERN.sub(r'', text)
        
    # Remove action text inside brackets/parentheses often generated by LLMs, e.g. [risos], (sorrindo)
    # We only remove short descriptive actions to avoid deleting actual content in parentheses
    text = BRACKET_PATTERN.sub('', text)
    
    # Remove markdown bold/italic asterisks and underscores
    # We remove the asterisks themselves, not the content, to avoid deleting emphasized words
    text = ASTERISK_PATTERN.sub('', text)
    text = UNDERSCORE_PATTERN.sub('', text)
    
    # Remove markdown headers (#)
    text = HASH_PATTERN.sub('', text)
    
    # Remove internal media tags before parsing so it doesn't say "VIDEO LINK" out loud
    text = MEDIA_TAG_PATTERN.sub('', text)
    
    # Remove URLs so the TTS engine doesn't read them out
    text = URL_PATTERN.sub('', text)
    
    # Clean up double spaces left behind
    text = SPACE_PATTERN.sub(' ', text).strip()
    
    return text


def _detect_audio_format(data: bytes) -> str:
    """Detect audio format from magic bytes."""
    if len(data) < 4:
        return "unknown"
    # OGG/Opus
    if data[:4] == b'OggS':
        return "ogg"
    # MP3 frame sync or ID3 tag
    if data[:3] == b'ID3' or (data[0] == 0xFF and (data[1] & 0xE0) == 0xE0):
        return "mp3"
    # WAV/RIFF
    if data[:4] == b'RIFF':
        return "wav"
    # FLAC
    if data[:4] == b'fLaC':
        return "flac"
    # AAC/M4A
    if len(data) >= 8 and data[4:8] == b'ftyp':
        return "m4a"
    return "unknown"


def _convert_to_ogg_opus(audio_bytes: bytes) -> bytes:
    """Convert audio bytes to OGG/Opus using ffmpeg.

    Returns the converted bytes, or the original bytes if conversion fails.
    """
    # Detect input format
    detected = _detect_audio_format(audio_bytes)
    logger.info(f"[TTS] Input audio: {len(audio_bytes)} bytes, detected format: {detected}")

    # If already OGG, no conversion needed
    if detected == "ogg":
        logger.info("[TTS] Audio is already OGG, skipping conversion")
        return audio_bytes

    # Determine file extension for temp file
    ext_map = {"mp3": ".mp3", "wav": ".wav", "flac": ".flac", "m4a": ".m4a"}
    ext = ext_map.get(detected, ".bin")

    tmp_in_path = ""
    tmp_out_path = ""
    try:
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp_in:
            tmp_in.write(audio_bytes)
            tmp_in_path = tmp_in.name

        tmp_out_path = tmp_in_path.rsplit(".", 1)[0] + ".ogg"

        # Try conversion with auto-detect first
        result = subprocess.run(
            [
                "ffmpeg", "-y",
                "-i", tmp_in_path,
                "-c:a", "libopus",
                "-b:a", "64k",
                "-vn",
                tmp_out_path,
            ],
            capture_output=True,
            timeout=30,
        )

        if result.returncode == 0 and os.path.exists(tmp_out_path):
            with open(tmp_out_path, "rb") as f:
                converted = f.read()
            if len(converted) > 100:  # Sanity check
                logger.info(
                    f"[TTS] Converted {len(audio_bytes)} bytes {detected} -> "
                    f"{len(converted)} bytes OGG/Opus"
                )
                return converted

        # Log full error
        stderr_full = result.stderr.decode("utf-8", errors="replace") if result.stderr else "(no stderr)"
        logger.warning(
            f"[TTS] ffmpeg conversion failed (rc={result.returncode}). "
            f"STDERR (last 600): {stderr_full[-600:]}"
        )

        # If detected format is unknown, the file might not be valid audio
        # Return as-is and let the system handle it
        logger.warning(f"[TTS] Returning raw {detected} audio bytes as fallback")
        return audio_bytes

    except FileNotFoundError:
        logger.warning("[TTS] ffmpeg not found, returning raw audio bytes")
        return audio_bytes
    except Exception as e:
        logger.warning(f"[TTS] Conversion error: {e}, returning raw audio bytes")
        return audio_bytes
    finally:
        for path in [tmp_in_path, tmp_out_path]:
            try:
                if path and os.path.exists(path):
                    os.unlink(path)
            except OSError:
                pass


def _convert_to_mp4_aac(audio_bytes: bytes) -> bytes:
    """Convert audio bytes to MP4/AAC using ffmpeg.

    Returns the converted bytes, or the original bytes if conversion fails.
    """
    # Detect input format
    detected = _detect_audio_format(audio_bytes)
    logger.info(f"[TTS] Input audio: {len(audio_bytes)} bytes, detected format: {detected}")

    # Determine file extension for temp file
    ext_map = {"mp3": ".mp3", "wav": ".wav", "flac": ".flac", "m4a": ".m4a"}
    ext = ext_map.get(detected, ".bin")

    tmp_in_path = ""
    tmp_out_path = ""
    try:
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp_in:
            tmp_in.write(audio_bytes)
            tmp_in_path = tmp_in.name

        tmp_out_path = tmp_in_path.rsplit(".", 1)[0] + ".mp4"

        # Try conversion with auto-detect first
        result = subprocess.run(
            [
                "ffmpeg", "-y",
                "-i", tmp_in_path,
                "-c:a", "aac",
                "-b:a", "64k",
                "-vn",
                tmp_out_path,
            ],
            capture_output=True,
            timeout=30,
        )

        if result.returncode == 0 and os.path.exists(tmp_out_path):
            with open(tmp_out_path, "rb") as f:
                converted = f.read()
            if len(converted) > 100:  # Sanity check
                logger.info(
                    f"[TTS] Converted {len(audio_bytes)} bytes {detected} -> "
                    f"{len(converted)} bytes MP4/AAC"
                )
                return converted

        # Log full error
        stderr_full = result.stderr.decode("utf-8", errors="replace") if result.stderr else "(no stderr)"
        logger.warning(
            f"[TTS] ffmpeg conversion failed (rc={result.returncode}). "
            f"STDERR (last 600): {stderr_full[-600:]}"
        )
        return audio_bytes

    except FileNotFoundError:
        logger.warning("[TTS] ffmpeg not found, returning raw audio bytes")
        return audio_bytes
    except Exception as e:
        logger.warning(f"[TTS] Conversion error: {e}, returning raw audio bytes")
        return audio_bytes
    finally:
        for path in [tmp_in_path, tmp_out_path]:
            try:
                if path and os.path.exists(path):
                    os.unlink(path)
            except OSError:
                pass



def create_text_to_speech_tool(config: Dict[str, Any]) -> FunctionTool:
    """Create the text_to_speech tool for LoopAgent.

    Args:
        config: The configuration dict, must contain 'provider' (e.g. 'elevenlabs', 'fish')
                and provider-specific settings.
    """
    provider_name = config.get("provider", "elevenlabs")

    async def text_to_speech(
        text: str,
        tool_context: Optional[ToolContext] = None,
    ):
        """Generates speech from text using the configured TTS provider and stores it in artifacts."""
        try:
            text = _clean_text_for_tts(text)
            
            if not text or not text.strip():
                return {"status": "failed", "error": "Text cannot be empty"}

            if len(text) > 5000:
                return {
                    "status": "failed",
                    "error": f"Text too long ({len(text)} characters). Maximum allowed is 5000 characters.",
                }

            logger.info(f"Generating speech with {provider_name} for text: {len(text)} chars")

            try:
                provider = get_tts_provider(provider_name)
            except ValueError as e:
                return {"status": "failed", "error": str(e)}

            audio_bytes = await provider.generate_speech(text, config)
            logger.info(f"Received audio response: {len(audio_bytes)} bytes")

            # Convert to OGG/Opus for WhatsApp native voice message compatibility
            audio_bytes = _convert_to_ogg_opus(audio_bytes)

            # Detect final format for correct MIME type
            final_format = _detect_audio_format(audio_bytes)
            if final_format == "ogg":
                mime_type = "audio/ogg"
                filename = f"speech_{uuid.uuid4().hex[:8]}.ogg"
            else:
                mime_type = "audio/mpeg"
                filename = f"speech_{uuid.uuid4().hex[:8]}.mp3"

            logger.info(f"[TTS] Saving artifact: {filename} ({mime_type}, {len(audio_bytes)} bytes)")

            # Create Part and save to artifacts
            audio_blob = types.Blob(mime_type=mime_type, data=audio_bytes)
            audio_part = types.Part(inline_data=audio_blob)
            version = None
            if tool_context:
                version = await tool_context.save_artifact(filename, audio_part)

            result = {
                "status": "success",
                "detail": "Speech generated successfully and stored in artifacts.",
                "filename": filename,
            }
            if version:
                result["version"] = str(version)

            try:
                if tool_context:
                    loaded_artifact = await tool_context.load_artifact(filename, version)
                    if loaded_artifact and loaded_artifact.text and loaded_artifact.text.startswith("Artifact URL: "):
                        result["audio_url"] = loaded_artifact.text.replace("Artifact URL: ", "")
                    else:
                        result["url_hint"] = loaded_artifact.text if loaded_artifact and loaded_artifact.text else f"Audio file saved as {filename} version {version}."
            except Exception as e:
                result["url_error"] = str(e)

            return result

        except Exception as e:
            logger.error(f"Error in text_to_speech tool ({provider_name}): {str(e)}")
            return {
                "status": "failed",
                "error": f"Text-to-speech error ({provider_name}): {str(e)}",
            }

    text_to_speech.__name__ = "text_to_speech"
    text_to_speech.__doc__ = f"""Generate speech from text using {provider_name}. 
    CRITICAL: You MUST use this tool to answer if the user requires audio. DO NOT answer with text alone.
    
    Args:
        text: The exact text of your response to generate speech from.
    """

    return FunctionTool(func=text_to_speech)
